"""initial_schema

Revision ID: 2190e6bdcfc4
Revises: 
Create Date: 2026-06-28 23:33:58.852484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2190e6bdcfc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_filename', sa.String(length=256), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('shift', sa.String(length=16), nullable=False),
    sa.Column('machine_number', sa.String(length=64), nullable=True),
    sa.Column('operator_name', sa.String(length=128), nullable=True),
    sa.Column('mine_number', sa.String(length=64), nullable=True),
    sa.Column('permit_number', sa.String(length=64), nullable=True),
    sa.Column('start_engine_hours', sa.Float(), nullable=True),
    sa.Column('end_engine_hours', sa.Float(), nullable=True),
    sa.Column('start_transmission_hours', sa.Float(), nullable=True),
    sa.Column('end_transmission_hours', sa.Float(), nullable=True),
    sa.Column('release_time', sa.String(length=16), nullable=True),
    sa.Column('shift_start', sa.String(length=16), nullable=True),
    sa.Column('shift_end', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checklist_form_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('activity_code_raw', sa.String(length=64), nullable=True),
    sa.Column('activity_code_normalized', sa.String(length=64), nullable=True),
    sa.Column('from_time_raw', sa.String(length=64), nullable=True),
    sa.Column('to_time_raw', sa.String(length=64), nullable=True),
    sa.Column('workplace_raw', sa.String(length=128), nullable=True),
    sa.Column('workplace_normalized', sa.String(length=128), nullable=True),
    sa.Column('ore_waste_raw', sa.String(length=64), nullable=True),
    sa.Column('ore_waste_normalized', sa.String(length=64), nullable=True),
    sa.Column('loads_raw', sa.String(length=64), nullable=True),
    sa.Column('loads_normalized', sa.String(length=64), nullable=True),
    sa.Column('remarks_raw', sa.Text(), nullable=True),
    sa.Column('remarks_normalized', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_form_id'], ['checklist_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checklist_form_id', sa.Integer(), nullable=False),
    sa.Column('total_shift_minutes', sa.Float(), nullable=True),
    sa.Column('release_time', sa.String(length=16), nullable=True),
    sa.Column('release_delay_minutes', sa.Float(), nullable=True),
    sa.Column('daily_service_duration_minutes', sa.Float(), nullable=True),
    sa.Column('production_duration_minutes', sa.Float(), nullable=True),
    sa.Column('breakdown_duration_minutes', sa.Float(), nullable=True),
    sa.Column('idle_duration_minutes', sa.Float(), nullable=True),
    sa.Column('availability_minutes', sa.Float(), nullable=True),
    sa.Column('utilization_ratio', sa.Float(), nullable=True),
    sa.Column('downtime_ratio', sa.Float(), nullable=True),
    sa.Column('engine_hours_delta', sa.Float(), nullable=True),
    sa.Column('engine_hours_valid', sa.Boolean(), nullable=True),
    sa.Column('engine_hours_validation_message', sa.String(length=256), nullable=True),
    sa.Column('transmission_hours_delta', sa.Float(), nullable=True),
    sa.Column('safety_meeting_detected', sa.Boolean(), nullable=True),
    sa.Column('change_of_shift_detected', sa.Boolean(), nullable=True),
    sa.Column('unmatched_gaps_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_form_id'], ['checklist_forms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_form_id')
    )
    op.create_table('daily_check_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checklist_form_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('check_item', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('is_service_action', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_form_id'], ['checklist_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_ocr_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checklist_form_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', sa.String(length=256), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=64), nullable=True),
    sa.Column('is_table_cell', sa.Boolean(), nullable=False),
    sa.Column('is_header', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_form_id'], ['checklist_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cleaned_activity_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checklist_form_id', sa.Integer(), nullable=False),
    sa.Column('activity_entry_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('activity_code', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.String(length=16), nullable=True),
    sa.Column('end_time', sa.String(length=16), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('workplace', sa.String(length=128), nullable=True),
    sa.Column('ore_waste', sa.String(length=64), nullable=True),
    sa.Column('loads', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('inference_reason', sa.String(length=128), nullable=True),
    sa.Column('is_inferred', sa.Boolean(), nullable=True),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_entry_id'], ['activity_entries.id'], ),
    sa.ForeignKeyConstraint(['checklist_form_id'], ['checklist_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cleaned_activity_events')
    op.drop_table('raw_ocr_fields')
    op.drop_table('daily_check_entries')
    op.drop_table('checklist_analytics')
    op.drop_table('activity_entries')
    op.drop_table('checklist_forms')
    # ### end Alembic commands ###
